// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PKD_PocketEvents","status":true,"description":"(v.1.0)[BASIC] Allow you spawn Events during game with placement select","parameters":{"TemplatesMap":"2","GlobalExceptRegions":"[\"20\"]","PlacementsList":"[\"{\\\"eventId\\\":\\\"1\\\",\\\"animationId\\\":\\\"121\\\",\\\"gridVisiblity\\\":\\\"true\\\",\\\"sSwitch\\\":\\\"A\\\",\\\"exceptRegions\\\":\\\"[\\\\\\\"10\\\\\\\",\\\\\\\"60\\\\\\\"]\\\",\\\"onlyRegions\\\":\\\"[]\\\"}\",\"{\\\"eventId\\\":\\\"2\\\",\\\"animationId\\\":\\\"121\\\",\\\"gridVisiblity\\\":\\\"true\\\",\\\"sSwitch\\\":\\\"A\\\",\\\"exceptRegions\\\":\\\"[]\\\",\\\"onlyRegions\\\":\\\"[]\\\"}\",\"{\\\"eventId\\\":\\\"3\\\",\\\"animationId\\\":\\\"121\\\",\\\"gridVisiblity\\\":\\\"false\\\",\\\"sSwitch\\\":\\\"A\\\",\\\"exceptRegions\\\":\\\"[]\\\",\\\"onlyRegions\\\":\\\"[\\\\\\\"3\\\\\\\"]\\\"}\",\"{\\\"eventId\\\":\\\"4\\\",\\\"animationId\\\":\\\"121\\\",\\\"gridVisiblity\\\":\\\"true\\\",\\\"sSwitch\\\":\\\"None\\\",\\\"exceptRegions\\\":\\\"[]\\\",\\\"onlyRegions\\\":\\\"[\\\\\\\"10\\\\\\\"]\\\"}\"]"}}
];
